### ISSUE TITLE
Support "Google-Style" History URLs

### ISSUE THREAD

**Issue by mseele** [gilberto-torrezan/gwt-views#10]
It would be cool if gwt-views (optionaly) support "Google-Style" History URLs:
- https://mail.google.com/mail/u/0/#inbox/1550d864d4f8f768
- https://translate.google.de/#de/en/Essen
- https://translate.google.de/#en/de/Play

They work with "segments" instead of "key-value" parameters.

It would be very easy to implement: Somewhere the user has to define with style he wants, depending on that style, the URLToken only need to parse the url in a different style.

I've tried a "dirty hack" to implement it by overriding URLToken. This doesn't work cause com.github.gilbertotorrezan.gwtviews.rebind.NavigationManagerGenerator uses URLToken instead of my "overriden" URLToken class (lines 100 / 166 / 279 / 184) ;)

This is my "dirty hack" i've tried:

```
public class SegmentsURLToken extends URLToken {

    private List<String> fSegments;

    /**
     * Creates a new URLToken using the current state of the application.
     */
    public SegmentsURLToken() {
        super();
    }

    /**
     * Creates a new URLToken using the provided token.
     * 
     * @param completeToken
     *            The History token to be parsed
     */
    public SegmentsURLToken(String completeToken) {
        super(completeToken);
    }

    /**
     * Clones a URLToken, copying the id and all parameters.
     * 
     * @see #clone()
     */
    public SegmentsURLToken(URLToken source) {
        super(source);
        if (source instanceof SegmentsURLToken) {
            this.fSegments = new ArrayList<>(((SegmentsURLToken) source).getSegments());
        }
    }

    @Override
    public void setToken(String completeToken) {
        this.fSegments = new ArrayList<>();
        String[] splitted = completeToken.split("/"); //$NON-NLS-1$
        if (splitted.length > 0) {
            setId(splitted[0]);
            for (int i = 1; i < splitted.length; i++) {
                this.fSegments.add(splitted[i]);
            }
        } else {
            super.setToken(completeToken);
        }
    }

    public List<String> getSegments() {
        return this.fSegments;
    }

    @Override
    public String toString() {
        if (this.fSegments != null && this.fSegments.size() > 0) {
            StringBuilder builder = new StringBuilder(getId());

            for (String segment : this.fSegments) {
                builder.append("/").append(segment); //$NON-NLS-1$
            }

            return builder.toString();
        }
        return super.toString();
    }

}
```

**Comment by gilberto-torrezan** [comment]
Thanks for the suggestion! I'll think about some way to allow the user to control the way the URLTokens are created, so you could create the tokens the way you want.

**Comment by gilberto-torrezan** [comment]
Fixed. Now you can set your URLTokenFactory at the NavigationManager by doing:

``` java
NavigationManager.setURLTokenFactory(new CustomURLTokenFactory());
```

... and at your CustomURLTokenFactory you can create the URLTokens the way you want:

``` java
public class CustomURLTokenFactory extends URLTokenFactory {
    @Override
    public URLToken createToken(String completeToken) {
        return new CustomURLToken(completeToken);
    }
}
```

**Comment by mseele** [comment]
Perfect. Can you please update maven with the 1.4.0 release?

**Comment by gilberto-torrezan** [comment]
Hi @mseele , sorry for the half-release. I released on maven central but somehow something went wrong and I had to redeploy. Everything should be fine now.

The package isn't visible at the search.maven.org yet, but you can download it without problems from maven itself.
