### ISSUE TITLE
Support for dependency injection

### ISSUE THREAD

**Issue by natros** [gilberto-torrezan/gwt-views#2]
How can I integrate with [Google Gin](https://code.google.com/p/google-gin/) or any other dependency injection framework?

Thanks.

**Comment by gilberto-torrezan** [comment]
For that you'll need to create a custom Presenter, which creates the View widgets by injection, using the framework you like.

Something like this:

``` java
public class MyPresenter implements Presenter<MyView> {
    private final MyWidgetGinjector injector = GWT.create(MyWidgetGinjector.class);

    @Override
    public MyView getView(URLToken url){
        MyView myView = injector.getMyView();
        return myView;
    }
}
```

MyView:

``` java
@View(value = "myview", customPresenter = MyPresenter.class)
public class MyView extends Composite {
//...
}
```

**Comment by natros** [comment]
So, I have to create a Presenter for each view I have and handle de caching.

**Comment by gilberto-torrezan** [comment]
Unfortunately yes. There could be an annotation (or a parameter on the View annotation) stating to create a Presenter which uses GIN, but that would make the whole framework dependant on that lib, which is not desirable. Do you have a suggestion on what could be made to make life easier for dependency injection?

**Comment by gilberto-torrezan** [comment]
Answering my own question, I just deployed the 1.1.0 version with a new parameter to the View annotation: injector.

``` java
@View(value = "myview", injector = MyInjector.class)
public class MyView extends Composite {
//...
}
```

That way you don't need to create a custom Presenter when you want to use dependency injection.

**Comment by natros** [comment]
I'm not sure if this is the best solution. Isn't this going to create a new injector for each view?

I was thinking something like this

``` java
NavigationManager.setDefaultObjectFactory(MyInjector.class)
```

or

``` java
NavigationManager.setDefaultObjectFactory(GWT.create(MyInjector.class))
```
