### ISSUE TITLE
Use the not found view in different view containers

### ISSUE THREAD

**Issue by natros** [gilberto-torrezan/gwt-views#6]
Hi,

I have two view containers, one for users and one for admins. Both containers have different designs. 
I have a not found view that is displayed inside the default container (the container for users). How can I have the same view displayed inside the admin container? Can I use the same view in different containers?

``` java
@View(value = "404", notFoundView = true)
public class NotFoundView extends Composite {
}
```

Thanks

**Comment by gilberto-torrezan** [comment]
Hi,

Good point, currently there's no way to just reuse the current `ViewContainer`: you need to use either the default one or define it by setting the `viewContainer` parameter at the `View`.

One workaround you can do is to disable the `ViewContainer` for the 404 view (by setting the `usesViewContainer = false`) and create a custom `Presenter` for it, that wraps the view into the right `ViewContainer` by inspecting the current URL token.

Something like this:

``` java
@View(value = "404", notFoundView = true, usesViewContainer = false, customPresenter = MyNotFoundPresenter.class)
public class NotFoundView extends Composite {
}
```

``` java
public class MyNotFoundPresenter implements Presenter<Widget> {
   @Override
   public Widget getView(URLToken url) {
            NotFoundView view = new NotFoundView(); //or use some sort of caching, like a static field
            HasViews container = null;
            String id = url.getId();
            switch (id) { //or some other logic to determine which container should be used
            //the presenter need to access the ViewContainer somehow. Maybe you can create them as singletons
            case "UrlThatDefineConatiner1ShouldBeUsed": container = MyContainer1.getInstance(); break;
            case "UrlThatDefineConatiner2ShouldBeUsed": container = MyContainer2.getInstance(); break;
            }
            container.showView(url, view);
            return (Widget) container;
       }
}
```
