### ISSUE TITLE
gwt-user 2.6 via Gradle

### ISSUE THREAD

**Issue by gte619n** [gilberto-torrezan/gwt-views#7]
Hello,

Using gradle, gwt-user (v2.6) gets pulled into my classpath, I believe this is from the Universal Analytics dependency. I can exclude it manually, but it creates a nasty conflict when running. It takes a minute to track down. 

I was wondering if we could decouple this in the next build? Especially with 2.8 so close!

Thanks,

E

**Comment by gilberto-torrezan** [comment]
Hi, thanks for your report.

I can force the project to avoid importing gwt-user itself, but the Universal Analytics I can't remove (unless I repackage it inside the project - practice that I don't like).

I'll take a look with Gradle to see what can be done (till today I only used Maven).

**Comment by gte619n** [comment]
Hey Gilberto,

Here's how I have it:

``` groovy
compile ("com.github.gilberto-torrezan:gwt-views:1.3.0"){
      exclude group:'com.google.gwt', module: 'gwt-user'
}
```

That's how I have it in my build file and it works as expected.

**Comment by gilberto-torrezan** [comment]
Fixed on v.1.3.1.
